sensor:
# Shows last FT8 frequency in kHz of decoded FT8 signal.
# Attributes contain timestamp, callsign etc.
  - name: "OpenWebRX-FT8"
    state_topic: "openwebrx/FT8"
    icon: mdi:radio
    value_template: '{{ ((value_json.freq | float) / 1000) | int }}'
    unit_of_measurement: "kHz"
    json_attributes_topic: "openwebrx/FT8"
    device:
      name: OpenWebRX
      identifiers: "webrx-monitoring"
      manufacturer: "klausgoepel"

# Shows last profile switched to. 
# Attributes contain source (SDR), e.g. Airspy
  - name: "OpenWebRX-RX"
    state_topic: "openwebrx/RX"
    icon: mdi:radio
    value_template: '{{ value_json.profile }}'
    json_attributes_topic: "openwebrx/RX"
    device:
      name: OpenWebRX
      identifiers: "webrx-monitoring"
      manufacturer: "klausgoepel"

