blueprint:
  name: WebRX-6m-alert
  description: Notification and spoken anouncement, when there is activity on the 6 m band.
  domain: automation

  input:
    webrx_ft8:
      name: webrx-ft8
      description: "Select the WebRX MQTT sensor OpenWebRX-FT8"
      selector:
        entity:
          filter:
            - domain: sensor

    notify_service:
      name: Notify service name
      description: Select the name of your notification service, where the notification should be sent.
      selector:
        text: {}
      default: notify.notify

    speak_on:
      name: Spoken Announcement
      description: Switch on, when you want a spoken announcement beside the notification. Requires Blueprint 'webrx-announce.yaml'.
      selector:
        boolean:
      default: true

# We need these global variables to use them in templates

variables:
  act_ft8:  !input webrx_ft8
  act_speak_on: !input speak_on

trigger_variables:
  tvar_ft8: !input webrx_ft8

# Only this trigger template needs to be changed for other blueprints

trigger:
  - platform: template
    value_template: >-
      {# Activity on 6 m but not a 9V1 station #} 
      {{
         ((state_attr(tvar_ft8,'freq') //1000000) == 50 ) and 
         ((((as_timestamp(now()) - 
         (state_attr(tvar_ft8,'timestamp')|int)/1000))) < 60) and
         ((state_var(tvar_ft8, 'callsign')| truncate(3,true,'',0)) != '9V1') 
      }}

action:

    # requires spell macro from macros.jinja
  - variables:
      call_spelled: |
        {% from 'macros.jinja' import spell %}
        {{ spell(state_attr(act_ft8, 'callsign')) }}
      loc_spelled: |
        {% from 'macros.jinja' import spell %}
        {{ spell( (state_attr(act_ft8, 'locator'))[0] +
                  (state_attr(act_ft8, 'locator'))[1]   
                ) }}   
      freq: |
        {{ states(act_ft8) | int // 1000 }}
    
    # Notification 
  - service: !input notify_service
    data:
      message: |-
        Station {{ state_attr( act_ft8, 'callsign') 
        }} in {{ state_attr( act_ft8, 'locator') }} active on {{
         freq }} MHz!
      title: OpenWebRX
    enabled: true
    
    # Anouncement: requires script blueprint webrx_announce
  - if:
    - condition: template
      value_template: >
        {{ (states('script.webrx_announce') == 'unknown') and act_speak_on }}
    then:
    - stop: "No announcement or blueprint missing "

    else:
    - service: script.webrx_announce
      data:
        message: |-
          The Station with callsign, {{ call_spelled 
          }}, in grid {{ loc_spelled 
          }}, is active on {{ freq }} MHz!
      enabled: act_speak_on

  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0

mode: single

