# Blueprint meta data
blueprint:
  name: WebRX-6m-alert
  author: 9V1KG Klaus
  homeassistant:
    min_version: 2024.7.0
  description: >
    # OpenWebRX 6m Alert 
       
    This blueprint allows a notification and an optional spoken anouncement, when call signs were decoded on 
    the 6 m band in FT-8.  
    
    An additional input text helper stores the recent call sign already announced to avoid repeating announcements. 
    Announcements of the same call sign on the same frequency are by default every 30 minutes.
    The blueprint requires the **OpenWebRX Integration** using MQTT and Rest sensors.  
    
    
    **Note:** If you select *Spoken Notification*, you need to install another blueprint script **`spoken-notification`** and the
    file **`macros.jinja`** first.
    For a comlpete description please see `hass-openwebrx` on [Github](https://github.com/9V1KG/hass-openwebrx/).
    
  source_url: https://github.com/9V1KG/hass-openwebrx/blob/b924e57d9e380f9e93384e5fdfa00bbc3334dc77/blueprints/automation/webrx-6m-alert.yaml
  domain: automation
  author: 9V1KG Klaus

  input:
    webrx_ft8:
      name: OpenWebRX FT-8 MQTT sensor
      description: Select the WebRX MQTT sensor, default is **`OpenWebRX-FT8`**.
      selector:
        entity:
          filter:
            - domain: sensor  

    last_call:
      name: Last call sign announced
      description: >
        Helper input text field to avoid too frequent announcements of the same call sign on the same band.
        Recent call sign and freq in MHz are stored, e.g. 9V1KG-7M
      selector:
        entity:
          filter:
            - domain: input_text
      default: input_text.last_call

    repeat_minutes:
      name: Repeat Delay Minutes
      description: Minutes delay between same callsign/frequency notifications (5 to 120 minutes).
      selector:
        number:
          min: 5
          max: 120
      default: 30

    notify_service:
      name: Notify service name
      description: Select the name of your notification service, where the notification should be sent.
      selector:
        text: {}
      default: notify.notify

    speak_on:
      name: Spoken Notification
      description: Switch on, when you want a spoken announcement beside the notification. Requires Blueprint 'webrx-announce.yaml'.
      selector:
        boolean:
      default: true
      
# We need these global variables to use them in templates

variables:
  act_ft8:  !input webrx_ft8
  act_speak_on: !input speak_on
  act_last_call: !input last_call
  act_tm: !input repeat_minutes
  
# Checks for entity_id based on friendly name 'WebRX-callsign-alert'
  bp_entid: >
    {% set entid = (states
     | selectattr('domain', 'eq', 'automation')
     | selectattr('attributes.friendly_name','eq','WebRX-callsign-alert') 
     | selectattr('state','eq','on')
     | map(attribute='object_id')
     | list) %}
    {% if entid | count != 0 %}{% set entid = 'automation.'+entid[0] %}{% endif %}

trigger_variables:
  tvar_ft8: !input webrx_ft8

trigger:
  - platform: template
    value_template: |-
      {# Activity on 6 m but not a 9V1 station #} 
      {{
         ( (state_attr(tvar_ft8,'freq')//1000000) == 50 ) 
         and 
         (((as_timestamp(now()) - (state_attr(tvar__ft8,'timestamp')|int)/1000)) < 60) 
         and
         ( (state_var(tvar__ft8, 'callsign')| truncate(3,true,'',0)) != '9V1') 
      }}
    id: 6m-activity

condition:
- condition: template
  value_template: >
    {% if entid %}{% set td = (as_timestamp(now()) - as_timestamp(state_attr(entid,'last_triggered')))/60 %}
    {{ state_attr('sensor.openwebrx_ft8','callsign') != states('input_text.last_call') or 
       state_attr('sensor.openwebrx_ft8','callsign') == states('input_text.last_call') and ( td > act_tm )
    }}{% endif %}
action:
  - variables:
      call_spelled: |
        {% if act_speak_on %}
        {% from 'macros.jinja' import spell %}
        {{ spell(state_attr(act_ft8, 'callsign')) }}
        {% endif %}
      loc_spelled: |
        {% if act_speak_on %}
        {% from 'macros.jinja' import spell %}
        {{ spell( (state_attr(act_ft8, 'locator'))[0] +
                  (state_attr(act_ft8, 'locator'))[1]   
                ) }}   
        {% endif %}
      freq: |
        {{ states(act_ft8) | int // 1000 }}

    # Notification
  - service: !input notify_service
    data:
      message: >
        Station {{ state_attr( act_ft8, 'callsign') 
        }} is active on {{ freq }} MHz. SNR: {{ state_attr( act_ft8, 'db') | int 
        }} dB
      title: OpenWebRX 6m alert
    enabled: true

    # Store call and freq in input_text helper
    
  - service: input_text.set_value
    target:
      entity_id: !input last_call
    data:
      value: >
        {{ state_attr(act_ft8,'callsign') }}-{{ states(act_ft8)| int //1000 }}M
    
    # Anouncement: requires script blueprint spoken-notification.yaml

  - if:
    - condition: template
      value_template: >
        {% set scrid = (states
         | selectattr('domain', 'eq', 'script')
         | selectattr('attributes.friendly_name','eq','Spoken Notification') 
         | map(attribute='object_id')
         | list) %}
        {{ ( scrid != 0) and act_speak_on }}
    then:
    - stop: "Spoken notification off or blueprint script missing"

    else:
    - service: script.spoken_notification
      data:
        message: |-
          The Station with the call sign, {{ call_spelled 
          }}, in locator grid {{ loc_spelled 
          }}, is active on {{ freq 
          }} MHz! The signal to noise ratio is {{
           state_attr( act_ft8, 'db') | int }} Decibel.
      enabled: act_speak_on

  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0

mode: single
