blueprint:
  name: WebRX-antarctica-alert
  description: Notification and spoken anouncement, when a station in Antarctica is active.
  domain: automation

  input:
    webrx_ft8:
      name: webrx-ft8
      description: "Select the WebRX MQTT sensor OpenWebRX-FT8"
      selector:
        entity:
          filter:
            - domain: sensor  

    notify_service:
      name: Notify service name
      description: Select the name of your notification service, where the notification should be sent.
      selector:
        text: {}
      default: notify.notify

    speak_on:
      name: Spoken Announcement
      description: Switch on, when you want a spoken announcement beside the notification. Requires Blueprint 'webrx-announce.yaml'.
      selector:
        boolean:
      default: true
      
# We need these global variables to use them in templates

variables:
  act_ft8:  !input webrx_ft8
  act_speak_on: !input speak_on
  
trigger_variables:
  tvar_webrx_ft8: !input webrx_ft8

# Only this trigger template needs to be changed for other blueprints

trigger:
  - platform: template
    value_template: |-
      {# Second letter of the locator field #}
      {% set ltrs = ['A','B','C','D'] %}
      {{ (state_attr(tvar_webrx_ft8,'locator') | list)[1] in ltrs }}
    id: Activity-Antarctica

action:

    # requires spell macro from macros.jinja
  - variables:
      call_spelled: |
        {% from 'macros.jinja' import spell %}
        {{ spell(state_attr(act_ft8, 'callsign')) }}

      loc_spelled: |
        {% from 'macros.jinja' import spell %}
        {{ spell( (state_attr(act_ft8, 'locator'))[0] +
                  (state_attr(act_ft8, 'locator'))[1]   
                ) }}   
      freq: |
        {{ states(act_ft8) | int // 1000 }}

    # Notification 
  - service: !input notify_service
    data:
      message: >
        Antarctica station {{ state_attr( act_ft8, 'callsign') 
        }} in {{ state_attr( act_ft8, 'locator') }} is active on {{
         states(act_ft8) | int //1000 }} MHz!
      title: OpenWebRX
    enabled: true
    
    # Anouncement: requires script blueprint webrx_announce

  - if:
    - condition: template
      value_template: >
        {{ (states('script.webrx_announce') == 'unknown') and act_speak_on }}
    then:
    - stop: "No announcement or blueprint missing "

    else:
    - service: script.webrx_announce
      data:
        message: |-
          Ham radio station from Antarctica with the callsign {{ call_spelled 
          }}, in locator grid {{ loc_spelled 
          }}, was decoded on {{ freq }} MHz!
      enabled: act_speak_on
      
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0

mode: single

