blueprint:
  name: WebRX-6m-alert
  description: Notification and spoken anouncement, when there is activity on the 6 m band.
  domain: automation

  input:
    webrx_ft8:
      name: webrx-ft8
      description: "Select the WebRX MQTT sensor OpenWebRX-FT8"
      selector:
        entity:
          filter:
            - domain: sensor  

    notify_service:
      name: Notify service name
      description: Select the name of your notification service, where the notification should be sent.
      selector:
        text: {}
      default: notify.notify

# We need these global variables to use them in templates

variables:
  act_ft8:  !input webrx_ft8

trigger_variables:
  tvar_webrx_ft8: !input webrx_ft8

trigger:
  - platform: template
    value_template: >-
      {# Activity on 6 m but not a 9V1 station #} 
      {{
         ((state_attr(tvar_webrx_ft8,'freq') //1000000) == 50 ) and 
         ((((as_timestamp(now()) - 
         (state_attr(tvar_webrx_ft8,'timestamp')|int)/1000))) < 60) and
         ((state_var(tvar_webrx_ft8, 'callsign')| truncate(3,true,'',0)) != '9V1') 
      }}
    id: Activity-6m

action:

    # requires spell macro from macros.jinja
  - variables:
      call_spelled: |
        {% from 'macros.jinja' import spell %}
        {{ spell(state_attr(act_ft8, 'callsign')) }}
      loc_spelled: |
        {% from 'macros.jinja' import spell %}
        {{ spell( (state_attr(act_ft8, 'locator'))[0] +
                  (state_attr(act_ft8, 'locator'))[1]   
                ) }}   
      freq: |
        {{ states(act_ft8) | int // 1000 }}
    
    # Notification 
  - service: !input notify_service
    data:
      message: |-
        Station {{ state_attr( act_ft8, 'callsign') 
        }} in {{ state_attr( act_ft8, 'locator') }} active on {{
         freq }} MHz!
      title: OpenWebRX
    enabled: true

    # Anouncement: requires script blueprint webrx_announce
  - service: script.webrx_announce
    data:
      message: |-
        The Station with callsign {{ call_spelled 
        }}, in locator grid {{ loc_spelled 
        }}, is active on {{ freq }} MHz!

  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0

mode: single
