blueprint:
  name: WebRX-announce
  description: Spoken anouncements of WebRX alarms using TTS
  domain: script
  input:

    tts-entity:
      name: tts-entity
      description: Select available tts entity like 'tts.home_assistant_cloud'
      selector:
        entity:
          filter:
            - domain: tts  

    media-play:
      name: media-player
      description: Select your available media player
      selector:
        entity:
          filter:
            - domain: media_player

alias: WebRX Announcement

variables:
  message: {}

sequence:
  - if:
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.living_room_2
            state: idle
          - condition: state
            entity_id: media_player.living_room_2
            state: paused
          - condition: state
            entity_id: media_player.living_room_2
            state: playing
    then:
      - service: tts.speak
        target:
          entity_id: !input tts-entity
        data:
          cache: true
          message: >
            {{message}}     
          media_player_entity_id: !input media-play
    else:
      - stop: Media player not ready

icon: mdi:account-voice
mode: single
